name: DAL test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dal_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Move to the ./Project/backend directory
      run: cd ./Project/backend

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true --local &&
        poetry install --only main

    - name: Move to ./Project/backend/dal directory
      run: cd ./Project/backend/dal

    - name: Run pytest
      run: poetry run pytest