name: DAL test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dal_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install python dependencies
      run: |
        cd ./Project/backend/api
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.path {project-dir}.venv &&
        poetry config virtualenvs.in-project true --local &&
        poetry install --only main

    - name: Run pytest
      run: |
        cd ./Project/backend/api
        poetry run pytest dal