name: End to end Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run E2E test for all services
        run: |
          cd ./Project
          docker compose build
          docker compose up -d
          chmod +x e2e.sh
          ./e2e.sh
          docker compose down